### PR TITLE
Cypress 10 version

### PR DESCRIPTION
**Pull request by piotrpog**
### Description

Updated cypress to version 10, latest dotenv in composer, twig template fix

### Related issues

There are two issues with the database seed file. 

First - admin login data in exmple cypress config is not correct. Can you update config with correct login? Or modify database.

Second - discounts defined in control panel and used by tests have usage limit set to zero. Because of that, cart test does not pass - these discounts cannot be applied. Can you update these discounts (I didnt wanted to tinked with database).

### CODE REVIEW

**Comment by nfourtythree** [comment]
HI @piotrpog 

Thank you for this.

There are a number of things in this PR and I would prefer to keep the concerns separate.

I have created a new PR specifically for updating to Cypress version 10: https://github.com/craftcms/spoke-and-chain/pull/132

If you could check that branch out and see if it works for you that would be very helpful.

We can then get that merged into `stable` and you can subsequently bring your PR up to date with it.

Thanks.

**Comment by piotrpog** [comment]
@nfourtythree Just tested cypress 10 branch, works great.
Would be great if you updated seed.sql file to resolve issue with discount.

**Comment by nfourtythree** [comment]
@piotrpog `seed.sql` has been updated for the max usages: https://github.com/craftcms/spoke-and-chain/commit/4b14db5f09d9392c7548daac59b2024a0234cd9f

The Cypress branch has been merged into `stable`. You should now be able to merge that branch into your PR branch to bring it up to date.

This PR can then become the PHP dot env PR and we can check it over.

Thanks!

**Comment by nfourtythree** [comment]
Hi @piotrpog 

I tried to bring your forked branch up to date with `stable` and then isolate the `phpdotenv` changes but unfortunately, I don't have write access to your forked repository.

I, therefore, made a new branch and made the changes there along with a new PR: https://github.com/craftcms/spoke-and-chain/pull/133

I will close this PR now as it is covered by the other ones that we have discussed.

Thanks!

**Pull request closed without merging**
