### PR TITLE
Convert to Vite.js & Docker

### PR DESCRIPTION
**Pull request by khalwat**
This is conversion of the Craft CMS demo site [Spoke and Chain](https://craftcms.com/demo) to a Docker-ized setup that uses [Vite.js](https://vitejs.dev/) modern frontend tooling.

### CODE REVIEW

**Comment by brandonkelly** [comment]
Thanks for the PR! We discussed this internally and decided against it, because the support + technical debt costs outweigh the benefit. We OS’d these sites so they can serve as an educational resource, particularly for the Craft side of things, not so much for the front-end. So the easier it is to get up and running for newcomers, the better, and providing an alternate installation method would add unnecessary complexity.

That said, you’re welcome to keep your fork around, and we would certainly consider a Vite-specific PR down the road once Nitro v3 is out and supports it.

**Comment by khalwat** [comment]
> So the easier it is to get up and running for newcomers, the better, and providing an alternate installation method would add unnecessary complexity.

@brandonkelly The site is _far_ easier to get up and running using the fork I made; that was one of the points of it honestly.

You just need to clone the repo, and do:
```
make dev
```
With Nitro, you have to clone the repo, do a bunch of setup, answer a bunch of questionnaire questions from the Nitro CLI, and even then you're stuck with having to install and run NPM locally because Nitro doesn't support it.

Compare the instructions: 

Nitro: https://github.com/craftcms/spoke-and-chain#environment

Docker: https://github.com/nystudio107/spoke-and-chain#initial-setup

...and fewer issues as well: https://github.com/craftcms/spoke-and-chain/issues/19 & https://github.com/craftcms/spoke-and-chain/issues/22

I totally get not wanting to take on the tech debt, and that reason alone is reason to reject the PR imo -- but "easier to get up and running" is backwards.

It's currently much more difficult to get it up and running in Nitro.

**Comment by brandonkelly** [comment]
There’s no way we would ditch the Nitro installation instructions, as we’re committed to making it the simplest & best way to run Craft locally for the 80% of people who want something that Just Works.

**Comment by brandonkelly** [comment]
To clarify, even if the Dockerfile route is arguably easier/better (for now), adding it as a second installation method would add confusion and mixed signaling for newcomers, which makes it worse. And there’s no way we would ditch the Nitro installation instructions in favor of this, as we’re committed to making it the simplest & best way to run Craft locally for the 80% of people who want something that Just Works.

**Comment by khalwat** [comment]
> To clarify, even if the Dockerfile route is arguably easier/better (for now), adding it as a second installation method would add confusion and mixed signaling for newcomers, which makes it worse. And there’s no way we would ditch the Nitro installation instructions in favor of this, as we’re committed to making it the simplest & best way to run Craft locally for the 80% of people who want something that Just Works.

That makes sense that you are committed to Nitro; I just wanted to clarify the point, because currently, it is definitely not the easiest way to get it up and running locally.

And yes, if you accepted the PR, I would assume that you would only be including instructions for the single `make dev` setup method, since the point is to allow people to easily spin up the site locally as a demo of Craft CMS, and not the apparatus around it.

**Pull request closed without merging**
